# Generated by Django 5.2.1 on 2025-05-15 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024, verbose_name='message')),
                ('delay', models.PositiveSmallIntegerField(choices=[(0, 'отправка сразу'), (1, 'отправка с задержкой в 1 час'), (2, 'отправка с задержкой в 1 день')], verbose_name='delay')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecipientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(blank=True, max_length=150, null=True, verbose_name='recipient in email')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients_email', to='notify.notification', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'recipient in email',
                'verbose_name_plural': 'recipients in email',
            },
        ),
        migrations.CreateModel(
            name='RecipientTG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=150, verbose_name='recipient in tg')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients_tg', to='notify.notification', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'recipient in TG',
                'verbose_name_plural': 'recipients in TG',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка')], max_length=10, verbose_name='status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='error message')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='notify.notification', verbose_name='notification')),
                ('recipient_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='notify.recipientemail', verbose_name='recipient in email')),
                ('recipient_tg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='notify.recipienttg', verbose_name='recipient in tg')),
            ],
            options={
                'verbose_name': 'notification log',
                'verbose_name_plural': 'notification logs',
            },
        ),
    ]
